spring:
  profiles:
    active: agent,mybatis,prod
  datasource:
    url: jdbc:mysql://localhost:3306/ip_agent_pool
    username: root
    password: wcj520600
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      enable: true
  task:
    scheduling:
      pool:
        size: 10


