agent:
  ip-agents:
    - site-name: "http://www.66ip.cn/"
      analyzeTr: "//div[@class='containerbox boxindex']//table/tbody/tr"
      position:
        ip: 1
        port: 2
        anonymity: 4
        address: 3
        updateTime: 5
      rules:
        updateTime:
          fomatter: io.github.ipagentpool.spider.fomatter.IP66StringToDateFormatter
      nextLinkRegex: "http://www.66ip.cn/\\d+.html"
    - site-name: "https://www.89ip.cn/"
      analyzeTr: "//div[@class='layui-col-md8']//table/tbody/tr"
      position:
        ip: 1
        port: 2
        anonymity: -1
        address: 3
        updateTime: 5
      rules:
        updateTime:
          fomatter: io.github.ipagentpool.spider.fomatter.IP89StringToDateFormatter
      nextLinkRegex: "https://www.89ip.cn/index_\\d+.html"
    - site-name: "https://free.kuaidaili.com/free/"
      analyzeTr: "//div[@id='list']/table/tbody/tr"
      position:
        ip: 1
        port: 2
        anonymity: 3
        address: 5
        updateTime: 7
      nextLinkRegex: "https://free.kuaidaili.com/free/inha/\\d+/"
    - site-name: "https://ip.ihuan.me/"
      analyzeTr: "//div[@class='table-responsive']/table/tbody/tr"
      position:
        ip: 1
        port: 2
        anonymity: 7
        address: 3
        updateTime: 10
      nextLinkRegex: "https://ip.ihuan.me/\\?page=\\w+"
      rules:
        ip:
          rule: "/a/text()"
        address:
          rule: "/a/text()"
          multi: true
        anonymity:
          rule: "/a/text()"
        updateTime:
          fomatter: io.github.ipagentpool.spider.fomatter.IHuanStringToDateFormatter
    - site-name: "http://www.ip3366.net/"
      analyzeTr: "//div[@id='list']/table/tbody/tr"
      position:
        ip: 1
        port: 2
        anonymity: 3
        address: 6
        updateTime: 8
      nextLinkRegex: "http://www.ip3366.net/\\?stype=1&page=\\d+"
      rules:
        updateTime:
          fomatter: io.github.ipagentpool.spider.fomatter.IP336StringToDateFormatter
    - acquire-type: Passive
      acquire-proxy-url: http://webapi.http.zhimacangku.com/getip?num=1&type=2&pro=&city=0&yys=0&port=1&time=1&ts=0&ys=0&cs=1&lb=1&sb=0&pb=4&mr=1&regions=
      host: "webapi.http.zhimacangku.com"
      token-url: https://wapi.http.linkudp.com/index/users/login_do
      username: "18682766240"
      password: "wcj520600"

